dataset:
  name: 'mp3d'
  image_root_dir: data/mp3d_skybox
  fov: 90
  rot: 45
  resolution: 512
  crop_size: 512
  seed: 0

train:
  lr: 0.0002

model:
  model_type: pano_outpainting
  model_id: stabilityai/stable-diffusion-2-inpainting
  single_image_ft: False
  guidance_scale: 9.
  diff_timestep: 50
    
